"""add extra images to design

Revision ID: 08fea449a44a
Revises: 
Create Date: 2025-10-20 22:11:06.941434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08fea449a44a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_image1_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('extra_image2_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.drop_column('extra_image2_url')
        batch_op.drop_column('extra_image1_url')

    # ### end Alembic commands ###
